import { test, expect } from "@playwright/test";
test("creates a synthetic case, advances triage and traces its notification", async ({
  page,
}) => {
  await page.goto("/");
  await expect(
    page.getByRole("heading", {
      name: "Da entrada à resolução, sem perder o rastro.",
    }),
  ).toBeVisible();
  await page
    .getByRole("button", { name: "Nova solicitação", exact: true })
    .click();
  const title = "Synthetic browser demo " + Date.now();
  await page.getByLabel("Título", { exact: true }).fill(title);
  await page
    .getByLabel("Descrição", { exact: true })
    .fill("Fictional data generated by the browser test.");
  await page
    .getByRole("button", { name: "Criar solicitação", exact: true })
    .click();
  const details = page.getByRole("complementary", {
    name: "Detalhes da solicitação",
  });
  await expect(details.getByRole("heading", { name: title })).toBeVisible();
  await expect(details.getByRole("tab", { name: /Histórico/ })).toBeVisible();
  await expect(
    details.getByRole("tab", { name: "Entrega do evento" }),
  ).toHaveCount(0);
  await page.getByRole("button", { name: "Mapa", exact: true }).click();
  await expect(
    page.getByRole("heading", {
      name: "Componentes que executam a demonstração.",
    }),
  ).toBeVisible();
  await expect(
    page
      .getByLabel("Diagrama dos sistemas CareQueue")
      .getByText("Express API", { exact: true }),
  ).toBeVisible();
  await expect(
    page.getByRole("heading", {
      name: "Como uma solicitação vira uma notificação confiável.",
    }),
  ).toHaveCount(0);
  await page.getByRole("button", { name: "Fluxo", exact: true }).click();
  await expect(
    page.getByRole("heading", {
      name: "Como uma solicitação vira uma notificação confiável.",
    }),
  ).toBeVisible();
  await expect(page.getByText("Cases + History + Outbox")).toBeVisible();
  await expect(
    details.getByText("Notificação simulada salva", { exact: true }),
  ).toBeVisible({ timeout: 15000 });
  await expect(
    details.getByText("1 notificação(ões) · efeito protegido por eventId", {
      exact: true,
    }),
  ).toBeVisible();
  await expect(
    details.getByText("correlationId", { exact: true }),
  ).toBeVisible();
  await details
    .getByRole("button", { name: "Avançar para em triagem" })
    .click();
  await expect(
    details.getByRole("button", { name: "Avançar para atribuída" }),
  ).toBeVisible();
  await details.getByRole("button", { name: "Avançar para atribuída" }).click();
  await expect(
    details.getByRole("button", { name: "Avançar para resolvida" }),
  ).toBeVisible();
  await details.getByRole("button", { name: "Avançar para resolvida" }).click();
  await expect(
    details.getByRole("button", { name: "Solicitação resolvida" }),
  ).toBeDisabled();
  await details.getByRole("tab", { name: /Histórico/ }).click();
  await expect(details.getByRole("listitem")).toHaveCount(4);
  await page.getByRole("button", { name: "Fluxo", exact: true }).click();
  await expect(
    page.getByText("docker compose stop rabbitmq", { exact: true }),
  ).toBeVisible();
  await expect(
    page.getByRole("heading", { name: "Repita a entrega" }),
  ).toBeVisible();
});
test("shows server errors with a correlation ID and preserves entered input", async ({
  page,
}) => {
  await page.goto("/");
  await page
    .getByRole("button", { name: "Nova solicitação", exact: true })
    .click();
  await page
    .getByLabel("Título", { exact: true })
    .fill("Synthetic rejected request");
  await page
    .getByLabel("Descrição", { exact: true })
    .fill("Fictional request for error display.");
  // Browser-only response fixture; runtime and reliability tests use real services.
  await page.route("**/api/cases", (route) =>
    route.request().method() === "POST"
      ? route.fulfill({
          status: 400,
          contentType: "application/json",
          headers: {
            "x-correlation-id": "87ba5cdd-9498-49e2-b271-24dccadf0b65",
          },
          body: JSON.stringify({
            error: { code: "VALIDATION_ERROR", message: "Invalid input" },
          }),
        })
      : route.continue(),
  );
  await page
    .getByRole("button", { name: "Criar solicitação", exact: true })
    .click();
  await expect(page.getByRole("alert")).toContainText("VALIDATION_ERROR");
  await expect(page.getByRole("alert")).toContainText(
    "87ba5cdd-9498-49e2-b271-24dccadf0b65",
  );
  await expect(page.getByLabel("Título", { exact: true })).toHaveValue(
    "Synthetic rejected request",
  );
});
test("works at a mobile viewport without horizontal document overflow", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await expect(
    page.getByRole("button", { name: "Nova solicitação", exact: true }),
  ).toBeVisible();
  expect(
    await page.evaluate(
      () => document.documentElement.scrollWidth <= window.innerWidth,
    ),
  ).toBe(true);
  await page.getByRole("button", { name: "Mapa", exact: true }).click();
  await expect(
    page.getByRole("heading", {
      name: "Componentes que executam a demonstração.",
    }),
  ).toBeVisible();
  await page.getByRole("button", { name: "Fluxo", exact: true }).click();
  await expect(
    page.getByRole("heading", {
      name: "Como uma solicitação vira uma notificação confiável.",
    }),
  ).toBeVisible();
  await page.getByRole("button", { name: "Glossário", exact: true }).click();
  await expect(
    page.getByRole("heading", {
      name: "Termos técnicos em linguagem simples.",
    }),
  ).toBeVisible();
  await expect(page.getByRole("heading", { name: "Outbox" })).toBeVisible();
  await expect(
    page.getByRole("heading", { name: "Idempotência" }),
  ).toBeVisible();
});
